name: Actualizar Lista Danju80 Cada 15 Minutos

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el Repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt || true

    - name: Ejecutar Script de Segmentación
      run: python actualizar_lista.py

    - name: Enviar Cambios a GitHub
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Registramos únicamente las 3 listas oficiales
        git add DANJU80 DANJU_MOVIES DANJU_SERIES
        
        if ! git diff --cached --quiet; then
          git commit -m "Automatización: Listas puras actualizadas"
          git pull origin main --rebase
          git push origin main
        else
          echo "Sin cambios detectados en las listas."
        fi
