name: System Maintenance Workflow

on:
  schedule:
    # Corre cada 20 minutos
    - cron: '*/20 * * * *'
  workflow_dispatch: # Botón manual

jobs:
  maintenance:
    runs-on: ubuntu-latest
    # Le damos 10 minutos para estar súper seguros
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install
        run: pip install requests

      - name: Run Magic
        run: python data_processor.py

      - name: Save Results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Danju80.txt system_cache.log
          git commit -m "🔄 Actualizacion por peticion" || exit 0
          git push
