name: Actualizador Inteligente Dany 80
on:
  workflow_dispatch: # Para que lo actives manual
  schedule:
    - cron: '*/15 * * * *' # Cada 15 minutos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests playwright
          playwright install chromium
          playwright install-deps chromium

      - name: Ejecutar Extractor
        run: python extractor.py

      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git add .
          git commit -m "Canales actualizados y progreso guardado [$(date +'%Y-%m-%d %H:%M')]" || exit 0
          git push
