name: Test Web Video Caster Clone

on:
  workflow_dispatch: # Esto nos da un botón en GitHub para correrlo manualmente cuando queramos

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-python: '3.10'

    - name: Instalar dependencias necesarias
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium --with-deps

    - name: Ejecutar el script clon de Web Video Caster
      run: python extractor_test.py

    - name: Guardar los enlaces obtenidos como reporte
      uses: actions/upload-artifact@v4
      with:
        name: reporte-de-canales
        path: resultados_trafico.txt
